#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with some requirements

sudo cp /etc/hosts /etc/hosts.new
sudo sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/g' /etc/hosts.new
sudo cp -f /etc/hosts.new /etc/hosts
